
---
- name: Docker Image Build
  hosts: docker
  tasks:
    - name: Copy Dockerfile
      copy:
       src: Dockerfile
       dest: /home/admin-user
    - name: Copy WAR file
      copy:
       src: target/app.war
       dest: /home/admin-user/app.war
    - name : Build Docker image
      command: docker build -t pressu31/zomato9 .
      args:
        chdir: /home/admin-user
    - name : Push Docker Image
      command: docker push pressu31/zomato9
- name: Deployment into Kubernetes Cluster
  hosts: eks
  tasks:
   - name: Copy K8s Deployment YAML 
     copy:
       src: DeploymentIntoK8sCluster.yml
       dest: /home/admin-user
   - name:  K8s Deployment 
     copy:
       src: LB-Service.yml
       dest: /home/admin-user
   - name : K8S Deployment
     command: kubectl apply -f DeploymentIntoK8sCluster.yml
   - name : LB Service
     command: kubectl apply -f LB-Service.yml
