---
- name: Docker Image Build
  hosts: docker
  become: yes
  tasks:
    - name: Copy Dockerfile to Docker host
      ansible.builtin.copy:
        src: Dockerfile
        dest: /home/admin-user/Dockerfile

    - name: Copy WAR file directory to Docker host
      ansible.builtin.copy:
        src: target/
        dest: /home/admin-user/target/
        mode: preserve
        remote_src: no
        directory_mode: yes

    - name: Build Docker image
      ansible.builtin.command:
        cmd: docker build -t pressu31/zomato9 .
      args:
        chdir: /home/admin-user

    - name: Push Docker image to DockerHub
      ansible.builtin.command:
        cmd: docker push pressu31/zomato9

- name: Deployment into Kubernetes Cluster
  hosts: eks
  become: yes
  tasks:
    - name: Copy Kubernetes Deployment manifest
      ansible.builtin.copy:
        src: DeploymentIntoK8sCluster.yml
        dest: /home/admin-user/DeploymentIntoK8sCluster.yml

    - name: Copy Kubernetes LoadBalancer Service manifest
      ansible.builtin.copy:
        src: LB-Service.yml
        dest: /home/admin-user/LB-Service.yml

    - name: Apply Kubernetes Deployment
      ansible.builtin.command:
        cmd: kubectl apply -f DeploymentIntoK8sCluster.yml
      args:
        chdir: /home/admin-user

    - name: Apply Kubernetes LoadBalancer Service
      ansible.builtin.command:
        cmd: kubectl apply -f LB-Service.yml
      args:
        chdir: /home/admin-user
